### ISSUE TITLE
Read from connection

### ISSUE THREAD

**Issue by hadley** [hadley/xml2#1]
Not urgent, but if you have some time @jeroenooms could you look at providing a function that reads from a connection. I presume you'll need to use `xmlReadIO`

**Comment by jeroenooms** [comment]
What's the advantage of reading from memory? You want to stream big xml?

**Comment by jeroenooms** [comment]
I had a first go at implementing the push parser interface. You can now do:

```r
doc <- xml_parse_con(url("http://www.xmlfiles.com/examples/cd_catalog.xml"))
```

Or:

```r
yeast <- system.file("examples/yeast_small-01.xml", package= "XML")
doc <- xml_parse_con(file(yeast))
```

I mostly copied your style from the memory parser. Feel free to clean up the code or change the R interface.

**Comment by hadley** [comment]
Awesome, thanks!
