### ISSUE TITLE
Doesn't install with GCC 6.

### ISSUE THREAD

**Issue by bhaskarvk** [hadley/xml2#114]
Platform : OS X (El Capitan)
S/W :  GCC 6 and libxml2 installed using homebrew

Setup

``` bash
# after setting up homebrew 

brew install gcc

# Use GCC 6 from now on.
export HOMEBREW_CC=gcc-6 
export HOMEBREW_CXX=g++6 

brew install libxml2
brew link libxml2 --force

brew tap caskroom/cask
brew cask install xquartz

brew install openblas --with-openmp 
brew install r --with-openblas --with-x11 --with-pango
```

Next Install xml2 package with the following Makevars

``` bash
CC=ccache gcc-6
CXX=ccache g++-6
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
LDFLAGS=-L/usr/local/lib -L/opt/X11/lib
CFLAGS=-I/usr/local/include -I/opt/X11/include  -mtune=native -g -O2 -Wall -pedantic -Wconversion
CXXFLAGS=-I/usr/local/include -I/opt/X11/include -std=c++11 -mtune=native -g -O2 -Wall -pedantic -Wconversion
PKG_LIBS = -fopenmp -lgomp
```

``` bash
Rscript -e 'install.packages("xml2")'
```

Output See attached file 1

[xml2-gcc.txt](https://github.com/hadley/xml2/files/382388/xml2-gcc.txt)

Next change Makevars to use default clang but still use homebrew's libxml2 and not the XCode supplied libxml2

``` bash
CC=ccache clang
CXX=ccache clang++
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
LDFLAGS=-L/usr/local/lib -L/opt/X11/lib
CFLAGS=-I/usr/local/include -I/opt/X11/include
CXXFLAGS=-I/usr/local/include -I/opt/X11/include -std=c++11 
```

This works, output attached file 2

[xml2-clang.txt](https://github.com/hadley/xml2/files/382391/xml2-clang.txt)

FWIW I had the same problem with the XML package as well and there too I had to use the clang compiler.

**Comment by bhaskarvk** [comment]
https://github.com/Homebrew/homebrew-science/issues/3718 seems related. I'll investigate more.

**Comment by ck37** [comment]
I ran into this problem as well. I was able to get it to compile by simply moving my old ~/.R/Makevars to another file and letting R use its defaults.
