### ISSUE TITLE
as_list.xml_node drops element names if any xml attributes exist

### ISSUE THREAD

**Issue by peterfoley** [hadley/xml2#115]
Reproducible example:
```{r}
txt <- "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<level_0 xmlns=\"http://whatever.com\">
  <level_1a> 
    <item>item1a</item>
  </level_1a>
  <level_1b>
    <item>item1b</item>
  </level_1b>
</level_0>
"

packageVersion("xml2")
library(xml2)
parsed <- as_list(read_xml(gsub("\\n\\s*","",txt)))
names(parsed)
```

The issue appears to be line 58 in:
`attributes(out) <- as.list(attr)`
which overwrites the names that were previously stored by line 52.

**Comment by leeper** [comment]
I am encountering the same issue with code that worked prior to xml2 v1.0.0 [but now fails](https://github.com/cloudyr/aws.s3/issues/60). I know this particular line of code was not changed in in the v1.0.0 release, but it appears to be interacting with other changes (probably in `xml_attrs()` methods).

Two difference changes could resolve this (for my use case):

1. Removing lines: https://github.com/hadley/xml2/blob/master/R/as_list.R#L58-L59
2. Replacing those lines with:

```R
 if (length(attr) > 0)
    attributes(out) <- c(attributes(out), as.list(attr))
```

The latter is probably better. Should I submit a PR?

**Comment by peterfoley** [comment]
There's [already a PR](https://github.com/hadley/xml2/pull/116) basically done for this issue, just needs to be merged. The original issue was motivated by xml2 v1.0.0 breaking `cloudyr/aws.ec2`, so hopefully it'll also fix what was broken for `cloudyr/aws.s3`.

**Comment by leeper** [comment]
Yes, it should. Thanks for that!

**Comment by jimhester** [comment]
Sorry for the delay in merging, the current master should now be fixed.
