### ISSUE TITLE
Improve error message for unrecognized HTML tags

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/xml2#120]
I ran into an issue parsing [this](http://spacefem.com/pregnant/due.php?use=EDD&m=09&d=10&y=16) page which I [posted about on SO](http://stackoverflow.com/questions/39281889).

At core is the sequence `<spoiler:3tbt4d3m>` found somewhere in the page's XML, which is not a recognized tag (at least from `xml2`'s perspective).

Debugging this would have been much facilitated with a better error message than:

> Error: Name spoiler:3tbt4d3m is not XML Namespace compliant [202]

For example, some mention that this was found as a tag in the file would have done wonders.

**Comment by jimhester** [comment]
The error message is coming from libxml2, not the R package so there is not much we can do without trying to catch and modify errors. This is not something I think is appropriate to do in this case.
