### ISSUE TITLE
Stock libxml2 broken on XCODE 8

### ISSUE THREAD

**Issue by jeroenooms** [hadley/xml2#127]
After upgrading OSX 10.11 to Xcode 8, I can no longer install `xml2` from source. Travis logs [show the same problem](https://travis-ci.org/hadley/xml2) for xcode8 + stock libxml2

```
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o xml2.so RcppExports.o connection.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_url.o xml2_xpath.o xml_push.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I suspect this is a bug in OS-X because Xcode 8 uses MacOSX10.12.sdk however I am still on 10.11. Hopefully the upgrade to OSX 10.12 will include a rebuild of `libxml2` which works with Xcode 8. 

I just can't figure out where `libsystem_symptoms.dylib` gets linked from. @s-u @krlmlr

**Comment by jeroenooms** [comment]
-This is a problem with Xcode 8 on OS-X 10.11. It has been resolved in OS-X 10.12.

 - https://github.com/Homebrew/brew/issues/972
 - https://stat.ethz.ch/pipermail/r-sig-mac/2016-September/012040.html

**Comment by jeroenooms** [comment]
The easiest way is just installing the binary package from CRAN. If you really want to install from source you can use this workaround: https://stat.ethz.ch/pipermail/r-sig-mac/2016-September/012046.html

**Comment by jimhester** [comment]
Can confirm BDR's workaround works fine, just ran into this myself.

**Comment by jeroenooms** [comment]
I incorporated this workaround in our travis file: https://github.com/hadley/xml2/commit/92a9ec9dd9de252fad9b26fe2bf726598ba9929d
