### ISSUE TITLE
More control over whitespace in output

### ISSUE THREAD

**Issue by hadley** [hadley/xml2#132]
So it's easier to do roundtrip conversions of html/xml without messing up existing whitespace

**Comment by hadley** [comment]
Actually, I think this just requires documenting the `format` argument

**Comment by hadley** [comment]
And maybe some testing and thinking about how to make it as easy as possible to read in a html file, modify it, and write it back out again.

**Comment by jimhester** [comment]
I documented the `format = TRUE` option in 610ae40. If you think more changes are needed we should reopen this issue.
