### ISSUE TITLE
Ambiguity about XML document versus its root node

### ISSUE THREAD

**Issue by jennybc** [hadley/xml2#136]
I use an example from `read_xml()` to make a small XML document two ways:
-   `read_xml()` with string input
-   `xml_new_document()` followed by several calls to `xml_add_child()`

These two paths to same destination leave you with `xml_document` objects that function differently. Is this intentional? It's pretty confusing. I think this issue might be a long-winded version of #106.

`read_xml()` says it returns an XML document. But it really returns the root node, with the class set to `c("xml_document", "xml_node")`. Which is true of _almost_ everything that inherits from `xml_document`.

``` r
library(magrittr)
library(xml2)
## taken from `read_xml()` examples
ex1 <- read_xml("<foo> <bar><baz /></bar> </foo>")
ex1
#> {xml_document}
#> <foo>
#> [1] <bar>\n  <baz/>\n</bar>
str(ex1)
#> List of 2
#>  $ node:<externalptr> 
#>  $ doc :<externalptr> 
#>  - attr(*, "class")= chr [1:2] "xml_document" "xml_node"
```

Now make the same XML by hand. Hold onto the document and the root node.

``` r
ex2_doc <- xml_new_document()
ex2_root <- ex2_doc %>%
  xml_add_child("foo") %>%
  xml_add_child("bar") %>%
  xml_add_child("baz") %>%
  xml_root()
ex2_doc
#> {xml_document}
str(ex2_doc)
#> List of 1
#>  $ doc:<externalptr> 
#>  - attr(*, "class")= chr "xml_document"
ex2_root
#> {xml_document}
#> <foo>
#> [1] <bar>\n  <baz/>\n</bar>
str(ex2_root)
#> List of 2
#>  $ node:<externalptr> 
#>  $ doc :<externalptr> 
#>  - attr(*, "class")= chr [1:2] "xml_document" "xml_node"
```

By the way, the problematic printing of `ex2_doc` above is fixed by #126. But nothing else here is. This printing problem is also noted in #106.

Up to explicit encoding, these are all the same when converted to character.

``` r
as.character(ex1)
#> [1] "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<foo><bar><baz/></bar></foo>\n"
as.character(ex2_doc)
#> [1] "<?xml version=\"1.0\"?>\n<foo><bar><baz/></bar></foo>\n"
as.character(ex2_root)
#> [1] "<?xml version=\"1.0\"?>\n<foo><bar><baz/></bar></foo>\n"
```

As noted in #106, the fact that `ex2_doc` is an XML document (and not the root node) means that `xml_structure()` doesn't work. #126 doesn't fix this.

``` r
xml_structure(ex1)
#> <foo>
#>   <bar>
#>     <baz>
xml_structure(ex2_doc)
#> Error in UseMethod("tree_structure"): no applicable method for 'tree_structure' applied to an object of class "xml_document"
xml_structure(ex2_root)
#> <foo>
#>   <bar>
#>     <baz>
```

`as_list()` says it turns an XML document into an R list, but there's no actual method for `xml_document`. So it only works for the objects of class `xml_document` that also inherit from `xml_node`.

``` r
as_list(ex1)
#> $bar
#> $bar$baz
#> list()
as_list(ex2_doc)
#> Error in UseMethod("as_list"): no applicable method for 'as_list' applied to an object of class "xml_document"
as_list(ex2_root)
#> $bar
#> $bar$baz
#> list()
```

**Comment by jimhester** [comment]
688a103 adds a `xml_new_root()` function, which creates a new document and root at the same time, which should provide a simpler way to create a new document without the inconsistencies noted in this issue.

For new code `xml_new_root()` should be used. `xml_new_document()` will remain available for now but should probably be deprecated in the future.
