### ISSUE TITLE
An error during read_xml causes hanging file connection

### ISSUE THREAD

**Issue by ReportMort** [hadley/xml2#144]
I noticed that if an xml file is malformed and you use `read_xml`, then the process fails with error as expected. However, if I try to edit the xml file and save it to fix the issue, RStudio generates the popup message indicating that this file is in use by another process. This is because `read_xml` does not close the file connection after erroring out on malformed xml.

![image](https://cloud.githubusercontent.com/assets/5299737/19895719/394d9074-a028-11e6-98f1-52eebb6b5b0d.png)

I've starting making sure that I always first open a connection to the xml file I'm trying to read, then read, and finally close that connection so that it's not left hanging in the event of an error

```
  tmp <- file('test.xml')
  open(tmp, "rb")
  doc <- tryCatch({
    read_xml(tmp)
  }, error=function(e){
    print(e)
    stop('The file does not contain valid XML.')
  }, finally = {
    close(tmp)
  })
```

I'm opening this issue because I think it's worth noting that the function does not recover and close the file connection (even when using `options="RECOVER"`).  I understand that this issue comes with the territory and it might not be good to change the package where it opens up connections before reading, but I think it's worth considering that files are always read as a connection to help ensure the connection is closed.

**Comment by jimhester** [comment]
`read_xml.connection` will automatically close the connection if it is not open, so you can just pass the connection directly into the function and it will close it on error (or a regular return)

```r
read_xml(file("test.xml"))
```

`read_xml.character` passes the file path directly to libxml2, so closing the file handle there is going to be much harder to do. If you want to edit the file you can always restart your R session in RStudio (Ctrl+Shift+F10).

**Comment by ReportMort** [comment]
Thanks @jimhester for suggestion. Using `read_xml(file("test.xml"))` is clever.
