### ISSUE TITLE
xml2 segfault reading xml file

### ISSUE THREAD

**Issue by statquant** [hadley/xml2#145]
As described [there](http://stackoverflow.com/questions/40417803/r-segfaulting-when-reading-xml?noredirect=1#comment68084771_40417803) loading the following `test.xml` file

```
<conf>
<Constraints>
<BETA>0</BETA>
</Constraints>
</conf>
```
```
R> library(xml2)
R> read_xml(
x=         encoding=  ...=       as_html=   options=   n=         verbose=   base_url=  
R> read_xml(x = 'test.xml')
```
causes a segfault.

**Comment by jimhester** [comment]
Apparently this was due to a [old version of xml2](http://stackoverflow.com/a/40425007/2055486) WFM.
