### ISSUE TITLE
Iterating over xml_children returns externalptr rather than nodeset

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/xml2#15]
Iterating over children in a document gives unexpected results:
```{r}
for (book in xml_children(x)) {
  xml_text(book)
}
  # Error in UseMethod("xml_text") : 
  # no applicable method for 'xml_text' applied to an object of class "externalptr"
```

Iterating and printing the children gives the following:
```
for (book in xml_children(x)) {
  print(book)
}
## <pointer: 0x7f81f5020f40>
## [[1]]
## <pointer: 0x7f81f50047c0>
## 
## [[2]]
## <pointer: 0x7f81f5004f80>
## 
## [[3]]
## <pointer: 0x7f81f5022db0>
## 
## [[4]]
## <pointer: 0x7f81f502a8c0>
```

**Comment by sjp** [comment]
I agree that this is a bit unexpected but we can still iterate over the nodes by getting the length of the nodeset and subsettings or using `seq_along()`.

An example below:

```r
library(xml2)
doc <- xml('<a><b><c>1</c><c>2</c><c>3</c></b></a>')
print(doc)
b_node <- xml_children(doc)
print(b_node)
c_nodes <- xml_children(b_node)

for (i in seq_along(c_nodes))
    print(c_nodes[i])
```

Perhaps we could create an `as.list()` method to turn an `xml_nodeset` (containing many nodes) into a list of `xml_nodeset`s (each with one node). That's basically what the `[` method is doing in the above code fragment.

@hadley what do you think about the idea of adding `as.list()` methods?

**Comment by hadley** [comment]
@sjp I think I was too clever here - it would be better to make a nodeset class that's just a list of nodes. I forgot that it's almost always a bad idea to override `length()` and `names()` because there are a lot of corner cases you can't handle.
