### ISSUE TITLE
xml_text does not trim "&nbsp"

### ISSUE THREAD

**Issue by rentrop** [hadley/xml2#151]
In my html-code i have `&nbsp` (i.e. non non-breaking space). If i try to get the the text via `xml_text(..., trim=TRUE)` it returns the non-breaking space instead of an empty string.
Is this a _feature_? IMHO the expected behavior would be to return an empty string...

Minimal-Example:
```
require(xml2)
space <- rawToChar(as.raw(c(0xc2, 0xa0)))
doc <- read_xml(paste0('<td style="text-align:left;">', space, '</td>'))
xml_text(doc, trim = TRUE) == "" # FALSE
charToRaw(xml_text(doc, trim = TRUE)) #[1] c2 a0
```

Workaround:
`stringi::stri_trim_both(xml_text(doc, trim = TRUE))` or `stringr::str_trim`

**Comment by rentrop** [comment]
@jimhester thanks for getting on this so fast. Unfortunately this fix opens another error:

Take this example:

```
devtools::install_github("hadley/xml2") # Version 1.0.0.9002
require(xml2)
doc <- read_html('<td>31.12.2010&nbsp;<br>€
                 </td>')
text_nodes <- xml_find_all(doc, ".//text()[normalize-space()]")
xml_text(text_nodes, trim = TRUE) # "31.12.2010" ""
```

So `xml_text` now removes the __€__-sign. 

The expected result would be:
```
stringi::stri_trim_both(text_nodes) # "31.12.2010" "€"
```

**Comment by jimhester** [comment]
Ok I refactored how this was being done, thanks for the reproducible example.

**Comment by rentrop** [comment]
Perfect, thanks
