### ISSUE TITLE
Feature request: sep argument for xml_text

### ISSUE THREAD

**Issue by izahn** [hadley/xml2#152]
`xml_text` extracts texts from a node and all child nodes. That is very convenient. It would be even more convenient if there were a way to insert a separator between the text retrieved from sibling or child nodes.

Currently
```
x <-  read_xml("<ul><li>this is item one</li><li>here comes item two</li></ul>")
xml_text(x)
```
produces
`# [1] "this is item onehere comes item two"`

It would be really nice if `xml_text` had a `sep` argument, so we could say (e.g.)

```
xml_text(x, sep = "\n")
```
rather than

```
paste(sapply(xml_children(x), xml_text), collapse = "\n")
```

**Comment by rentrop** [comment]
+1 This would be great. As a quick fix you could use my solution presented in https://github.com/hadley/rvest/issues/175. 

Using this on your example results in:

```
> html_text_collapse(x)
#[1] "this is item one\nhere comes item two"
```

**Comment by hadley** [comment]
This feels out of scope for xml2 to me. The job of xml2 is to give you low-level access to the xml tree, and this doesn't feel like that to me.

**Comment by izahn** [comment]
It makes sense that this is out of scope for the xml2 package, but... Where is the high-level user-friendly xml parsing package? Would this feature request be welcomed for `rvest::html_text`?

**Comment by hadley** [comment]
Yes, it would be more suitable for rvest, but it seems quite special purpose to me, and doing the operation by hand is quite easy and looks natural in a pipe:

```R
library(rvest)
library(purrr)

x <- read_xml("<root>
  <a><b>1</b> <b>2</b></a>
  <a><b>3</b></a>
</root>")

x %>% 
  xml_find_all("a") %>% 
  map_chr(. %>% xml_find_all("b") %>% xml_text() %>% paste(collapse = ", "))
```
