### ISSUE TITLE
xml_find_all() returns error with 'boolean' function in xpath selector

### ISSUE THREAD

**Issue by gothub** [hadley/xml2#154]
With `boolean()` function, `xml_find_all()` returns an error, while `xml_file_first()`
succeeds:

```
> mdoc <- read_xml( "<title>this is a great title</title>")
> selector <- 'boolean("/title")'
> xml_find_all(mdoc, selector)
Error: expecting an external pointer
> xml_find_first(mdoc, selector)
[1] TRUE
```

**Comment by jimhester** [comment]
`xml_find_first()` and `xml_find_all()` expect to return a node or nodeset. If you are trying to return a logical value you should use `xml_find_lgl()`.

**Comment by gothub** [comment]
@jimhester thanks for having a look. The documentation for `xml_find_first` states that it also either returns a `node` or a `nodeset` but it correctly evaluates the xpath expression and returns a logical. So is `xml_find_first` behaving as expected?

```
> mdoc <- read_xml( "<title>this is a great title</title>")
> selector <- 'boolean("/title")'
> class(xml_find_first(mdoc, selector))
[1] "logical"
```
