### ISSUE TITLE
Add cleanup script

### ISSUE THREAD

**Issue by jimhester** [hadley/xml2#155]
From [Configure and cleanup](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Configure-and-cleanup)
> *N.B.*: If the 'configure' script creates files, e.g. 'src/Makevars',
  you do need a 'cleanup' script to remove them.  Otherwise 'R CMD
  build' may ship the files that are created.

**Comment by jeroenooms** [comment]
Done
