### ISSUE TITLE
add support for connections to `write_xml`

### ISSUE THREAD

**Issue by lbartnik** [hadley/xml2#157]
`write_xml` accepts a file path as its second parameter. It could also accept a `connection` or even a broader list of outputs similar to `cat()`

**Comment by jimhester** [comment]
Sure we would probably accept a pull request implementing this, but I don't think we are going to implement it ourselves. `as.character()` will get you the text representation in memory if that is what you are after.

**Comment by hadley** [comment]
@jimhester we won't do it for this release, but it might be worthwhile to do next time, just to get more experience writing to connections (which ideally we should support anytime you can pass a filename)

**Comment by jimhester** [comment]
@lbartnik As of https://github.com/hadley/xml2/commit/0676f71be82488a8c8b32a8482ab08e0a2171966 you can use `as.character(..., format = TRUE)` and get equivalent formatting to `write_xml()`.
