### ISSUE TITLE
read_html crashes on Ubuntu when correct encoding is provided

### ISSUE THREAD

**Issue by armanabraham** [hadley/xml2#162]
### Description
read_html fails when using correct character encoding, but works when using incorrect encoding. This happens on Ubuntu (see session_info), but can't reproduce on Mac. 

Here is the error produced by the last command using the reproducible code below: 
> Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, : input conversion failed due to input error, bytes 0xFB 0x7C 0xB7 0x51 [6003]

Here is Sys.getlocale() on Ubuntu: 
"LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C"

### Reproducible Example
```r
# GET webpage that is encoded using Big5 (Chinese)
pg <- httr::GET("http://chinesenews.net.au")
# Identify encoding using rvest function, which returns incorrect 
# encoding as ISO-8859-1
enc1 <- rvest::guess_encoding(httr::content(pg, "raw"))$encoding[1]
# Use hack to identify the right encoding using a function from stringi package
enc2 <- as.character(
                as.data.frame(
                      stringi::stri_enc_detect(httr::content(pg, "raw"))[[1]])[1,1]) 
# So far so good. 
# Let's try to read_html with both encodings
# Using ISO-8859-1 encoding, there is no problem
ht1 <- xml2::read_html(pg, encoding=enc1) # Reads, but characters are distorted
# However, using correct (Big5) encoding crashes on Ubuntu
ht2 <- xml2::read_html(pg, encoding=enc2) 


```

<details>
<summary>Session Info</summary>

```r
devtools::session_info() # Paste output below
#> Session info ---------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Zulu                        
 date     2017-01-05                  

Packages -------------------------------------------------------
 package   * version    date      
 curl        2.3        2016-11-24
 devtools    1.12.0     2016-12-05
 digest      0.6.11     2017-01-03
 fictech   * 0.1.0      2017-01-03
 httr        1.2.1      2016-07-03
 magrittr  * 1.5        2014-11-22
 memoise     1.0.0      2016-01-29
 NLP         0.1-9      2016-02-18
 purrr       0.2.2      2016-06-18
 R6          2.2.0      2016-10-05
 Rcpp        0.12.8.3   2017-01-04
 rvest       0.3.2      2016-06-17
 selectr     0.3-1      2016-12-19
 slam        0.1-32     2014-04-02
 stringi     1.1.2      2016-10-01
 stringr     1.1.0      2016-08-19
 tm          0.6-2      2015-07-03
 triebeard   0.3.0      2016-08-04
 urltools    1.6.0      2016-10-17
 withr       1.0.2      2016-06-20
 xml2      * 1.0.0.9002 2017-01-04
 source                        
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 local                         
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 Github (RcppCore/Rcpp@f0442a0)
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.1.0)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 CRAN (R 3.2.3)                
 Github (hadley/xml2@78112cf) 
</details>

**Comment by jimhester** [comment]
I cannot reproduce this with the current CRAN release or devel master, can you confirm the issue still occurs with those versions?

``` r
xml2::read_html("http://chinesenews.net.au", encoding = "BIG5")
#> {xml_document}
#> <html>
#> [1] <head>\n<title>《澳華網》﹕澳大利亞新聞網一站門戶 - 悉尼日報Australian Chinese Daily News ...
#> [2] <body onselectstart="return dealSel()">\r\n\r\n<!-- skin begins -->\ ...
```

**Comment by armanabraham** [comment]
Still have the same error on Ubuntu ((16.04.1) after deleting the package and re-installing from CRAN. There is no problem running the same code on a Mac.  

Do you think that libxml2.so.2 library on Ubuntu might be the culprit? 

Here is the traceback: 

11: stop(list(message = "input conversion failed due to input error, bytes 0xFC 0x4C 0xA4 0x6A [6003]", 
        call = doc_parse_raw(x, encoding = encoding, base_url = base_url, 
            as_html = as_html, options = options), cppstack = list(
            file = "", line = -1L, stack = c("/usr/local/lib/R/site-library/xml2/libs/xml2.so(Rcpp::exception::exception(char const*)+0x79) [0x7f6a03dd6b09]", 
            "/usr/local/lib/R/site-library/xml2/libs/xml2.so(void Rcpp::stop<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&)+0x52) [0x7f6a03dd95f2]", 
            "/usr/local/lib/R/site-library/xml2/libs/xml2.so(handleError(void*, _xmlError*)+0xdf) [0x7f6a03dd88bf]", 
            "/usr/lib/x86_64-linux-gnu/libxml2.so.2(__xmlRaiseError+0x3d4) [0x7f6a03a33fa4]", 
            "/usr/lib/x86_64-linux-gnu/libxml2.so.2(xmlCharEncInput+0x2ca) [0x7f6a03a3099a]", 
            "/usr/lib/x86_64-linux-gnu/libxml2.so.2(+0x37755) [0x7f6a03a34755]", 
            "/usr/lib/x86_64-linux-gnu/libxml2.so.2(xmlSwitchToEncoding+0xa4) [0x7f6a03a36284]", 
            "/usr/lib/x86_64-linux-gnu/libxml2.so.2(htmlReadMemory+0x1b8) [0x7f6a03a8f268]", 
            "/usr/local/lib/R/site-library/xml2/libs/xml2.so(doc_parse_raw(Rcpp::Vector<24, Rcpp::PreserveStorage>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)+0x93) [0x7f6a03dd5af3]", 
            "/usr/local/lib/R/site-library/xml2/libs/xml2.so(xml2_doc_parse_raw+0x1a4) [0x7f6a03dd05b4]", 
            "/usr/lib/R/lib/libR.so(+0xd0d90) [0x7f6a1736bd90]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x74f) [0x7f6a173a24ff]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(+0x10ab26) [0x7f6a173a5b26]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(+0x13ba48) [0x7f6a173d6a48]", 
            "/usr/lib/R/lib/libR.so(+0x13be5b) [0x7f6a173d6e5b]", 
            "/usr/lib/R/lib/libR.so(+0x13c106) [0x7f6a173d7106]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(+0x10780b) [0x7f6a173a280b]", 
            "/usr/lib/R/lib/libR.so(+0x107ce8) [0x7f6a173a2ce8]", 
            "/usr/lib/R/lib/libR.so(+0xff6b5) [0x7f6a1739a6b5]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x180) [0x7f6a173a1f30]", 
            "/usr/lib/R/lib/libR.so(+0x10780b) [0x7f6a173a280b]", 
            "/usr/lib/R/lib/libR.so(+0x107ce8) [0x7f6a173a2ce8]", 
            "/usr/lib/R/lib/libR.so(+0xff6b5) [0x7f6a1739a6b5]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x180) [0x7f6a173a1f30]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(+0x102e93) [0x7f6a1739de93]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x180) [0x7f6a173a1f30]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(+0x13ba48) [0x7f6a173d6a48]", 
            "/usr/lib/R/lib/libR.so(+0x13bebb) [0x7f6a173d6ebb]", 
            "/usr/lib/R/lib/libR.so(+0x13c106) [0x7f6a173d7106]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(+0x1099b8) [0x7f6a173a49b8]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x541) [0x7f6a173a22f1]", 
            "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x4de) [0x7f6a173a396e]", 
            "/usr/lib/R/lib/libR.so(Rf_eval+0x31d) [0x7f6a173a20cd]", 
            "/usr/lib/R/lib/libR.so(Rf_ReplIteration+0x222) [0x7f6a173c9892]", 
            "/usr/lib/R/lib/libR.so(+0x12ec11) [0x7f6a173c9c11]", 
            "/usr/lib/R/lib/libR.so(run_Rmainloop+0x44) [0x7f6a173c9cc4]", 
            "/usr/lib/R/bin/exec/R(main+0x1b) [0x4007cb]", "/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f6a16cd5830]", 
            "/usr/lib/R/bin/exec/R(_start+0x29) [0x400809]"))))
10: .Call("xml2_doc_parse_raw", PACKAGE = "xml2", x, encoding, base_url, 
        as_html, options)
9: doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, 
       options = options)
8: read_xml.raw(raw, encoding = encoding, base_url = base_url, as_html = as_html, 
       options = options)
7: read_xml.connection(con, encoding = encoding, ..., as_html = as_html, 
       base_url = x, options = options)
6: read_xml.character(x, encoding = encoding, ..., as_html = TRUE, 
       options = options)
5: read_xml(x, encoding = encoding, ..., as_html = TRUE, options = options)
4: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
3: suppressWarnings(read_xml(x, encoding = encoding, ..., as_html = TRUE, 
       options = options))
2: read_html.default("http://chinesenews.net.au", encoding = "BIG5")
1: xml2::read_html("http://chinesenews.net.au", encoding = "BIG5")

**Comment by jimhester** [comment]
I think this is due to iconv differences on the two platforms, I am guessing part of the page is actually encoding in something other than BIG-5 and the linux iconv is being more conservative about parsing it than MacOS.

In any case I unfortunately don't think there are any changes we can do in xml2 to remedy this situation. 😞

**Comment by armanabraham** [comment]
Thank you for clarifying. Do you happen to know by chance if there is a better iconv for R?
