### ISSUE TITLE
Can't build xml2 with non-system-wide libxml2?

### ISSUE THREAD

**Issue by jonathanronen** [hadley/xml2#163]
Building this on a system where I don't have root access (so I have libxml and other libraries in a custom path, not `/usr`). I get the following error:

```
xml2_output.cpp: In function ‘Rcpp::IntegerVector xml_save_options()’:
xml2_output.cpp:45: error: ‘XML_SAVE_WSNONSIG’ was not declared in this scope
make: *** [xml2_output.o] Error 1 ERROR: compilation failed for package ‘xml2’
```

which I think might be because it's compiling with the system libxml, which might be too old?

`g++ -I/home/jronen/R-3.3.1/lib64/R/include -DNDEBUG -I../inst/include -I/usr/include/libxml2 -I/usr/local/include -I"/home/jronen/R-3.3.1/lib64/R/library/Rcpp/include" -I"/home/jronen/R-3.3.1/lib64/R/library/BH/include"   -fpic  -g -O2  -c xml2_output.cpp -o xml2_output.o`

Do you know how I can pass other flags to the compiler when installing this to tell it where to find the correct libxml, or if this is a different error?

Thx!!

**Comment by jimhester** [comment]
`R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"`

Also can you say what version of libxml2 is on your system? We should be able to add support for earlier versions as well.

**Comment by alexvorobiev** [comment]
(Sorry for copying my comment I added to that commit but we have rather strict policies and can't  use packages directly from github for work projects)...
When do you think this will be on CRAN? As it stands, the package can't be installed on RHEL 6.x because of the older libxml2.
Thanks!

**Comment by jimhester** [comment]
I can submit a point release soon, but I would like to verify this issue is fixed before doing so. @alexvorobiev Can you verify the current master fixes the installation issue?

**Comment by alexvorobiev** [comment]
@jimhester Yes, I was able to install from master with no issues.
