### ISSUE TITLE
sh: ./configure: No such file or directory

### ISSUE THREAD

**Issue by feinerer** [hadley/xml2#178]
Following error occurs when installing the package on OpenBSD with R version 3.4.0:

```
> devtools::install_github("hadley/xml2")
Downloading GitHub repo hadley/xml2@master
from URL https://api.github.com/repos/hadley/xml2/zipball/master
Installing xml2
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmpInIHFV/devtools952b587a2802/hadley-xml2-3eb7e69'  \
  --library='/home/feinerer/R' --install-tests 

* installing *source* package ‘xml2’ ...
sh: ./configure: No such file or directory
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/feinerer/R/xml2’
Error: Command failed (1)
```

The problem is likely that `#!/bin/bash` is hardcoded in configure. OpenBSD does not have `bash` in its base system. Even if you install a package for it, it is in `/usr/local/bin/bash`.

**Comment by jimhester** [comment]
Can we rely on `/use/bin/env bash` instead?

**Comment by feinerer** [comment]
Yes, that should work:
```
$ echo $0
ksh
$ /usr/bin/env bash
$ echo $0
bash
```
Alternatively, just use `/bin/sh` if you can avoid bash-specific functionality. That would be the portable solution.

**Comment by jimhester** [comment]
We need to use bash for the configure script to work properly on Solaris. See (https://github.com/hadley/xml2/commit/79d368914d038b4cd9669f6680ed3d283ed1911c#commitcomment-17202406) for the particulars.
