### ISSUE TITLE
difficulty forming tbl_df from XML

### ISSUE THREAD

**Issue by jennybc** [hadley/xml2#24]
This may very well be user error, but I'd love to understand what I am doing wrong.

Example below starts with XML inspired by the Google Sheets "cell feed" (but greatly simplified). My goal is to get a `tbl_df` with one row per cell.

I am trying to use the pipe operator and a `dplyr`-ish workflow but I am puzzled by an unexpected variable that is an XML node set. If I eliminate an intermediate step, I even get a fatal error.

What am I doing wrong?

```r
suppressPackageStartupMessages(library("dplyr"))
library("xml2")

x <- read_xml('
<feed>
  <title type="text">Africa</title>
  <author>
    <name>gspreadr</name>
    <email>gspreadr@gmail.com</email>
  </author>
  <entry>
    <title type="text">A1</title>
    <content type="text">country</content>
  </entry>
  <entry>
    <title type="text">B1</title>
    <content type="text">continent</content>
  </entry>
  <entry>
    <title type="text">A2</title>
    <content type="text">Algeria</content>
  </entry>
  <entry>
    <title type="text">B2</title>
    <content type="text">Africa</content>
  </entry>
</feed>
')

## get a nodeset containing the 'entry' nodes
x1 <- x %>%
  xml_find_all("//entry")

## then get the text of the title nodes
x2 <- x1 %>%
  xml_find_all(".//title") %>%
  xml_text()
x2 %>% str
#>  chr [1:4] "A1" "B1" "A2" "B2"
## it's a plain vanilla character vector YAY

## make a tbl_df from text in the title and content nodes
x3 <- x1 %>%
  data_frame(cell = xml_find_all(., ".//title") %>% xml_text(),
             value = xml_find_all(., ".//content") %>% xml_text())
x3
#> Source: local data frame [4 x 3]
#> 
#>               . cell     value
#> 1 <S3:xml_node>   A1   country
#> 2 <S3:xml_node>   B1 continent
#> 3 <S3:xml_node>   A2   Algeria
#> 4 <S3:xml_node>   B2    Africa
## what's up with this first variable `.` and how do I suppress its creation?
x3$`.` %>% class
#> [1] "xml_nodeset"
x3 %>% glimpse
#> Observations: 4
#> Variables:
#> Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L, : first argument must be atomic
## glimpse does not like this variable name?

## attempt to make same tbl_df but w/o the intermediate x1 object
x4 <- x %>%
  dplyr::data_frame(cell = xml_find_all(., "//entry//title") %>% xml_text(),
                    value = xml_find_all(., "//entry//content") %>% xml_text())
#> Error in data_frame_(lazyeval::lazy_dots(...)): arguments imply differing number of rows: 2, 4, 4
## this doesn't work at all

## get rid of the pipe SUCCESS
x5 <- data_frame(cell = xml_find_all(x1, ".//title") %>% xml_text(),
                 value = xml_find_all(x1, ".//content") %>% xml_text())
x5
#> Source: local data frame [4 x 2]
#> 
#>   cell     value
#> 1   A1   country
#> 2   B1 continent
#> 3   A2   Algeria
#> 4   B2    Africa
```

**Comment by timelyportfolio** [comment]
Looks like `%>%` is assuming `x1` is also the first argument to your `data.frame` call.  See if this fixes it.

```r
x3 <- data_frame(cell = xml_find_all(x1, ".//title") %>% xml_text(),
             value = xml_find_all(x1, ".//content") %>% xml_text())
```

**Comment by timelyportfolio** [comment]
Actually, think I found it in magrittr [here](https://github.com/smbache/magrittr#re-using-the-placeholder-for-attributes).

```r
x1 %>%
  {
     data_frame(cell = xml_find_all(., ".//title") %>% xml_text(),
             value = xml_find_all(., ".//content") %>% xml_text())
  }
```

**Comment by jennybc** [comment]
Yes @timelyportfolio this makes sense. So this is a magrittr user error, more than anything to do with xml2. Thanks.

**Comment by jennybc** [comment]
Let's just reframe this as [an example of the fiddliness of pipelines](https://twitter.com/hadleywickham/status/587692022863015936) that transition across object types, esp. from list-like objects to data.frame or vector.

**Comment by hadley** [comment]
Why do you prefer the pipe-y form of creating the data frame over the non-pipe-y form?

**Comment by jennybc** [comment]
Part of it is that, overall, things feel easier if I adopt a consistent way of doing things. Such as using pipes. But maybe I should operate differently when dealing with list-like things.

Here's code that's closer to real life, gathering stuff from various nooks and crannies of the XML:

```r
x1 <- req$content %>%
    xml2::xml_find_all("//feed:entry", ns) %>% {
      dplyr::data_frame(cell = xml2::xml_find_all(., ".//feed:title", ns) %>%
                          xml2::xml_text(),
                        edit_link = xml2::xml_find_all(., ".//feed:link[@rel='edit']", ns) %>%
                          xml2::xml_attr("href"),
                        cell_id = xml2::xml_find_all(., ".//feed:id", ns) %>%
                          xml2::xml_text(),
                        cell_alt = cell_id %>% basename())
    }
```
It felt concise/efficient to do with a pipe but maybe I should just create more intermediate objects? I am really open to advice. (You'll notice I still need to rewrite this to use `data_frame_()` to please R CMD check.)

**Comment by hadley** [comment]
I find creating intermediate objects to be fairly natural - they are often reasonable easy to name. In your case I'd also switch to using `xml_find_one()` once you have the entries - that should make failure more obvious if the structure changes (or is other than you expect)

```R
entries <- req$content %>% xml2::xml_find_all("//feed:entry", ns)

dplyr::data_frame(
  cell = entries %>% xml2::xml_find_one(".//feed:title", ns) %>% xml2::xml_text(),
  edit_link = entries %>% xml2::xml_find_one(".//feed:link[@rel='edit']", ns) %>% xml2::xml_attr("href"),
  cell_id = entries %>% xml2::xml_find_one(".//feed:id", ns) %>% xml2::xml_text(),
  cell_alt = cell_id %>% basename()
)
```

Rather than using `data_frame_` you could fix the R CMD check warning with:

```R
cell_id <-  xml2::xml_find_all(., ".//feed:id", ns) %>% xml2::xml_text()

dplyr::data_frame(
  cell = entries %>% xml2::xml_find_one(".//feed:title", ns) %>% xml2::xml_text(),
  edit_link = entries %>% xml2::xml_find_one(".//feed:link[@rel='edit']", ns) %>% xml2::xml_attr("href"),
  cell_id = cell_id,
  cell_alt = cell_id %>% basename()
)
```

But that all feels rather verbose, esp. if you're explicit about the function names. It's a bit better if you attach xml2;

```R
dplyr::data_frame(
  cell = entries %>% xml_find_one(".//feed:title", ns) %>% xml_text(),
  edit_link = entries %>% xml_find_one(".//feed:link[@rel='edit']", ns) %>% xml_attr("href"),
  cell_id = entries %>% xml_find_one(".//feed:id", ns) %>% xml_text(),
  cell_alt = cell_id %>% basename()
)
```

I wonder if it would be possible to attach the namespace to the xml document so it would become:

```R
dplyr::data_frame(
  cell = entries %>% xml_find_one(".//feed:title") %>% xml_text(),
  edit_link = entries %>% xml_find_one(".//feed:link[@rel='edit']") %>% xml_attr("href"),
  cell_id = entries %>% xml_find_one(".//feed:id") %>% xml_text(),
  cell_alt = cell_id %>% basename()
)
```

Alternatively, maybe this needs a bit more DSL magic

```R
dplyr::data_frame(
  cell = entries %x% ".//feed:title",
  edit_link = entries %x% ".//feed:link[@rel='edit']" %@% "href",
  cell_id = entries %x% ".//feed:id",
  cell_alt = cell_id %>% basename()
)
```

That assumes some coercion magic that `data_frame()` doesn't currently possess - but it wouldn't be too hard to have `data_frame()` call `as_column()` or similar on each input, and then you could have `as_column.xml_nodeset <- function(x) xml_text(x)`.

**Comment by hadley** [comment]
Would probably put those functions in rvest because xml2 is supposed to be fairly low level

**Comment by jennybc** [comment]
Thanks for all of this! I'll act on the bits that are already within my control.

I really like the idea of attaching the namespace to the XML document -- I'm always dragging it around. The extraction operators look very intriguing, where ever they end up.

**Comment by eibanez** [comment]
Very helpful thread and cool ideas! One question: how would you make the code above robust so that it still worked if one of the entries is missing a piece of information. For instance, if `B2` did not have a `content` child:

```
x <- read_xml('
<feed>
  <entry>
    <title type="text">A1</title>
    <content type="text">country</content>
  </entry>
  <entry>
    <title type="text">B1</title>
    <content type="text">continent</content>
  </entry>
  <entry>
    <title type="text">A2</title>
  </entry>
  <entry>
    <title type="text">B2</title>
    <content type="text">Africa</content>
  </entry>
</feed>
')
```
