### ISSUE TITLE
Please add a package documentation file (xml2-package.Rd)

### ISSUE THREAD

**Issue by maiermarco** [hadley/xml2#26]

**Comment by hadley** [comment]
Why?

**Comment by maiermarco** [comment]
mainly, because it's a convenient "starting point".
started using `xml2` yesterday - after loading it, i habitually typed `?xml2` to get the package doc and then go to the index of functions to get an overlook, etc.
since there's no package doc, i've had to look for the exported functions in the namespace, look up the help page for one (`?xml2::url_unescape`, i think), and then go to the index.
i don't know if it's just me, but when i want to access the manual pages for a pkg, not a specific function, i usually use `?pkgname`

**Comment by hadley** [comment]
You're generally better off using `help(package = xml2)`
