### ISSUE TITLE
"Premature end of line"

### ISSUE THREAD

**Issue by Ironholds** [hadley/xml2#3]
<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.10/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.10/ http://www.mediawiki.org/xml/export-0.10.xsd" version="0.10" xml:lang="arc">

Running read_xml on a file containing the above leads to:

> Error: Premature end of data in tag mediawiki line 1 [77]

**Comment by jeroenooms** [comment]
I think you either need to close the tag or end with `/>` to make it valid xml?

**Comment by Ironholds** [comment]
That'd do it. I guess the followup would be: could we have a 'skip' parameter for cases when the XML creator thinks it's a good idea to have pseudo-XML metadata in the file?

**Comment by hadley** [comment]
It seems like the `XML_PARSE_RECOVER` option should let you recover from errors like this, but it's not very well documented, so I can't tell whether it just can't recover from this problem, or I'm using it wrong.

**Comment by hadley** [comment]
Hmmm, it interacts poorly with the error handlers I set up to send libxml2 errors to R - sometimes a fatal error isn't actually fatal so I don't need to `stop()`. I'll need to think about how to work around this.

**Comment by hadley** [comment]
I've tried a few times and I can't trigger robust parsing in libxml2. If you can figure it out, I'd be happy to review a pull request, but for now xml2 will only work with valid xml.

**Comment by Ironholds** [comment]
*thumbs up*. I'll see if I can do anything and tail -n things if not :)

**Comment by yasineahmed** [comment]
Hello, has issue been resolved? 
Thanks
