### ISSUE TITLE
Feature request: xml validator / parser function or parameter

### ISSUE THREAD

**Issue by stephlocke** [hadley/xml2#31]
It would be very handy to have a function in this suite that tests whether a fragment is valid XML or HTML. Currently, you can only try performing a conversion and see if it errors or not.

```{r}
xmlfrag<-"<foo><bar /></foot>"

## Additional function
if(xml_validate(xmlfrag)){
read_xml(xmlfrag)
}else{
print(xmlfrag)
}
## Extended read_xml
xmlresult<-read_xml(xmlfrag, check=TRUE) # Output a TRUE or FALSE

```

**Comment by jeroenooms** [comment]
http://xmlsoft.org/html/libxml-valid.html

**Comment by cboettig** [comment]
It would be really nice if validation included schema validation, not just validating the XML.  As I see it, the ability to actually check if a document obeys a specified schema is one of the main reasons for providing data in XML in the first place and not just in JSON (even though I suppose schemas are beginning to pop up there to).

Thanks for `xml2` btw, avoiding segfaults is a beautiful thing! right now I guess `XML` is still our only option for serializing and validating though...

**Comment by jeroenooms** [comment]
http://www.xmlsoft.org/html/libxml-xmlschemas.html

**Comment by hadley** [comment]
I'd consider a pull request to implement this; otherwise it's unlikely to get high-enough on my priority list to implement.

**Comment by jeroenooms** [comment]
Added `xml_validate` in https://github.com/hadley/xml2/commit/a8ca948e5c9d61a69237d02342e3f8e6eeb3ad6e to validate xml 1.0 schemas.
