### ISSUE TITLE
Encoding not specified with xml_text

### ISSUE THREAD

**Issue by larmarange** [hadley/xml2#36]
Hi, 

I have some issue with encoding and `xml_text`. Let me try to describe.

Let's import an UTF-8 file: `content <- read_html("my_file.html", encoding = "UTF-8")`

Let's get the text from it: `text <- xml_text(content)`

Accented characters are not displayed properly. The result of `Encoding(text)` is unknown. If I manually specify `Encoding(text) <- "UTF-8"` then it's OK.

Would be great if `xml_text` could specify the appropriate encoding.

**Comment by hadley** [comment]
To help me test the problem, could you please verify that the following code gives incorrect results?

```R
x <- read_xml("<å>∫</å>")
xml_text(x)
xml_name(x)
```

**Comment by hadley** [comment]
BTW now that you've pointed it out it's really obvious what I did wrong.

**Comment by larmarange** [comment]
Don't worry. It's common for English speaker developer not to detect issues regarding encoding as they often don't use accented characters. ;-)

I verifed your code as requested:

```r
> x <- read_xml("<å>∫</å>")
> xml_text(x)
[1] "âˆ«"
> xml_name(x)
[1] "Ã¥"
```

In addition:

```r
> t <- xml_text(x)
> Encoding(t)
[1] "unknown"
> t
[1] "âˆ«"
> Encoding(t) <- 'UTF-8'
> t
[1] "∫"
```

**Comment by hadley** [comment]
Hmmm, not sure what I'm missing here. The code looks ok to me, but it definitely doesn't work.

**Comment by jimhester** [comment]
Are we sure this is still an issue? This is the output on my machine.

``` r
x <- read_xml("<å>∫</å>")
(t <- xml_text(x))
#> [1] "∫"
xml_name(x)
#> [1] "å"
Encoding(t)
#> [1] "UTF-8"
```

**Comment by hadley** [comment]
@jimhester did you check on windows? I forget the exact issue, but it's normally fine on the mac because utf-8 is the default.

**Comment by hadley** [comment]
I'm pretty sure this is now ok
