### ISSUE TITLE
nth-element XPath selection behavior different between XML,  xml2 v1.0 and xml2 v0.1.0.9000

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/xml2#39]
SO ref: http://stackoverflow.com/a/30558163/1457051

`xml_find_all("//table[6]/tbody/tr/td[8]")` worked in `xml2` v1.0 & `html_nodes(xpath="//table[6]/tbody/tr/td[8]")` works via the `XML` library. In v0.1.0.9000 of `xml2` I had to do:

    pg2 %>% xml_find_all("//table") %>% 
      as_list %>% 
      extract2(6) %>% 
      xml_find_all("./tbody/tr/td[8]")

SO post has the complete context, with salient parts reproduced below. Not sure if it's just me or if I'm doing something wrong.

    library(XML)
    library(rvest)
    library(magrittr)
    library(xml2)

    pg <- html("http://www.transfermarkt.nl/lionel-messi/leistungsdaten/spieler/28003/saison/2014/plus/1")
    pg %>% 
      html_nodes(xpath="//table[6]/tbody/tr/td[8]") %>% 
      xmlSApply(xpathApply, "boolean(./span[@class='kapitaenicon-table icons_sprite'])") %>% 
      which
    ## [1]  2 10 11 27

    # this worked in v1.0
    pg2 <- read_html("http://www.transfermarkt.nl/lionel-messi/leistungsdaten/spieler/28003/saison/2014/plus/1")
    pg2 %>% 
      xml_find_all("//table[6]/tbody/tr/td[8]") %>% 
      as_list %>% 
      sapply(function(x) {
        inherits(try(xml_find_one(x, "./span"), silent=TRUE), "xml_node")
      }) ## %>%  which # which won't work since this returns an empty list

    # this was an initial workaround for v0.1.0.9000
    pg2 %>% xml_find_all("//table") %>% 
      as_list %>% 
      extract2(6) %>% 
      xml_find_all("./tbody/tr/td[8]") %>% 
      as_list %>% 
      sapply(function(x) {
        inherits(try(xml_find_one(x, "./span"), silent=TRUE), "xml_node")
      }) %>% which

    Session info ---------------------------------------------------------
     setting  value                       
     version  R version 3.2.0 (2015-04-16)
     system   x86_64, darwin13.4.0        
     ui       RStudio (0.99.441)          
     language (EN)                        
     collate  en_US.UTF-8                 
     tz       America/New_York            

    Packages -------------------------------------------------------------
     package    * version    date       source                      
     bitops     * 1.0-6      2013-08-17 CRAN (R 3.2.0)              
     curl       * 0.5        2015-02-01 CRAN (R 3.2.0)              
     devtools   * 1.7.0      2015-01-17 CRAN (R 3.2.0)              
     httr       * 0.6.1      2015-01-01 CRAN (R 3.2.0)              
     magrittr     1.5        2014-11-22 CRAN (R 3.2.0)              
     Rcpp       * 0.11.5     2015-03-06 CRAN (R 3.2.0)              
     RCurl      * 1.95-4.5   2014-12-28 CRAN (R 3.2.0)              
     rstudioapi * 0.3.1      2015-04-07 CRAN (R 3.2.0)              
     rvest        0.2.0      2015-01-01 CRAN (R 3.2.0)              
     selectr    * 0.2-3      2014-12-24 CRAN (R 3.2.0)              
     stringr    * 0.6.2      2012-12-06 CRAN (R 3.2.0)              
     XML          3.98-1.1   2013-06-20 CRAN (R 3.2.0)              
     xml2         0.1.0.9000 2015-06-01 Github (hadley/xml2@ca0ae3c)

**Comment by hadley** [comment]
Could you please include a reprex in the issue?

**Comment by hadley** [comment]
Could you try making it a bit simpler? This looks ok to me:

```R
x <- read_xml("<a>
  <b><c>1-1</c><c>1-2</c><c>1-3</c><c>1-4</c></b>
  <b><c>2-1</c><c>2-2</c><c>3-3</c><c>4-4</c></b>
</a>")
xml_find_all(x, "//b[2]/c[3]")
```
