### ISSUE TITLE
Make sure it doesn't crash on solaris

### ISSUE THREAD

**Issue by hadley** [hadley/xml2#40]

**Comment by jeroenooms** [comment]
For the record, this email was sent to CRAN on June 6 (without response):

> The xml2 package fails a unit test on solaris with the message "Unsupported encoding ISO8859-1". This typically indicates that the libxml2 shared library was built --without-iconv.

> I am unable to reproduce this problem on either sparc-sun-solaris2.10 (32-bit) or x86_64-pc-solaris2.10 (64-bit). On both machines the package passes all checks (using CSWlibxml2-dev-2.9.1).

> Could it be that the version of libxml2_dev on the CRAN server is outdated? Or is there another build of libxml2.so installed on the server? Output from "ldd /opt/csw/lib/R/library/xml2/libs/xml2.so" would be very helpful.

**Comment by hadley** [comment]
Let's close this for now, and we'll re-open if BDR gives us more info.
