### ISSUE TITLE
DESCRIPTION should include URL and BugReports fields

### ISSUE THREAD

**Issue by cboettig** [hadley/xml2#42]
linking here

**Comment by hadley** [comment]
Snap!

**Comment by cboettig** [comment]
would it be unwise for `devtools` to try and guess these fields from the .git remote?

**Comment by hadley** [comment]
Are you thinking of doing that in `create()`? Or in `use_github()`? Or elsewhere

**Comment by cboettig** [comment]
You probably know better than I.  Not sure if most users have git bit in place when they run `create()`, so `use_github()` might make more sense.  

Alternatively, I'm wondering if there should be a kind of optional check function that checks (and helps create/populate?) for these kind of things that aren't required of a (CRAN) package...
