### ISSUE TITLE
Recommendation: Implement options = HUGE equivalent in read_html/read_xml

### ISSUE THREAD

**Issue by theRanalyst** [hadley/xml2#44]
I'm working with some rather large email files where the content of an email is saved as an html file. Using `read_html` on some of these files results in the following error (with traceback):
```
 Error: Excessive depth in document: 256 use XML_PARSE_HUGE option [1] 
10 stop(structure(list(message = "Excessive depth in document: 256 use XML_PARSE_HUGE option [1]", 
    call = NULL, cppstack = NULL), .Names = c("message", "call", 
"cppstack"), class = c("Rcpp::exception", "C++Error", "error", 
"condition"))) 
9 doc_parse_file(con, encoding = encoding, as_html = as_html) 
8 read_xml.character(x, encoding, ..., as_html = TRUE) 
7 read_xml(x, encoding, ..., as_html = TRUE) 
6 withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) 
5 suppressWarnings(read_xml(x, encoding, ..., as_html = TRUE)) 
4 read_html(contentLink) 
3 FUN(X[[i]], ...) 
2 lapply(X = X, FUN = FUN, ...) 
1 sapply(1:length(emails), function(idx) {
    attrs <- xml_attrs(emails[idx])[[1]]
    index <- attrs["index"]
    sender <- attrs["from"] ... 
```
I'd like to suggest adding something similar to the workaround offered [here](http://stackoverflow.com/questions/17154308/parse-xml-files-1-megabyte-in-r). If this is already available in the package, then please excuse my ignorance.

**Comment by theRanalyst** [comment]
So after spending the better part of today looking into this issue and trying to understand the error better and how - or better yet why - it should be addressed, I've realized that this actually probably isn't a good thing to implement in `xml2`. I originally understood the error to mean that the size of the file was too large, but in reality it's simply saying there are too many nested elements. This can be a good indication of a corrupt HTML file (which was my issue) and should probably keep just doing what it's doing: throwing an error. I'm going to close this as a non-issue.

**Comment by rkertesz** [comment]
In our case, having too many elements is a real issue. There should be some way to address this. 

Here is where the problem has been raised here for processing weather files ... https://github.com/dannycbowman/cageo-rnomads/issues/1
Here is some more on the issue ... 
http://stackoverflow.com/questions/33819103/parsing-small-web-page-with-xml2-throws-xml-parse-huge-error
