### ISSUE TITLE
Implement deduplication switch on xml_find_all

### ISSUE THREAD

**Issue by twcook** [hadley/xml2#45]
I can't imagine the use case for de-duplicating nodes automatically. However, please implement a switch to turn this off.  I need to be able to pull all instances of a node from the tree. 

Otherwise, a great package. Much easier to use than XML and I am hoping to replace XML with xml2. 

Thanks.

**Comment by hadley** [comment]
Can you please supply and reproducible example and some more motivation. Why do you want nodes repeated multiple times in the output?

**Comment by twcook** [comment]
I misunderstood what you meant by de-duplication. I see the output nodeset is what I expected.  In fact I still don't understand what you mean by de-duplication.  Do you have a reference explaining it in this context?

**Comment by hadley** [comment]
```R
library(xml2)

x <- read_xml("<a>
  <b></b>
  <b><c/></b>
</a>")

b <- xml_find_all(x, ".//b")
xml_find_all(b, "//*")
```

without de-duping the final result would contain every node in the document _twice_, because `//*` is applied to both nodes in `b`.  Does that make sense?

**Comment by twcook** [comment]
Okay. Thanks.
