### ISSUE TITLE
OS X Yosemite Issue with Homebrew and Solution

### ISSUE THREAD

**Issue by jlisic** [hadley/xml2#46]
I'm not sure how useful you will find this, but this might at least help with some support.

The issue is that it appears that pkg-config --cflags libxml-2.0 tends to return a nonexistent directory, namely /usr/include/libxml2.  This seems to occur on at least 7 macs between my own and some friends, all running yosemite.

The fix is to just search the libxml directory of homebrew before trying pkg-config.  The directory location should be sufficiently obscure not to impact other operating systems.

```bash
# Custom libxml2 path for compatibility with old XML package
if [ "$LIBXML_INCDIR" ]; then
  LIBXML_CFLAGS="-I$LIBXML_INCDIR"
  echo "User specified xml2 headers in $LIBXML_INCDIR."
# slightly annoying fix for homebrew / OSX
elif [ -r "/usr/local/opt/libxml2/include/libxml2/libxml/parser.h" ]; then
  LIBXML_CFLAGS="-I/usr/local/opt/libxml2/include/libxml2/"
  LIBXML_LIBS="-L/usr/local/opt/libxml2/lib -lxml2"
elif [ "$PKGCONFIG" ]; then
  LIBXML_CFLAGS=`pkg-config --cflags libxml-2.0`
  LIBXML_LIBS=`pkg-config --libs libxml-2.0`
elif [ -r "/usr/include/libxml2/libxml/parser.h" ]; then
  LIBXML_CFLAGS="-I/usr/include/libxml2/"
elif [ -r "/usr/local/include/libxml2/libxml/parser.h" ]; then
  LIBXML_CFLAGS="-I/usr/local/include/libxml2/"
elif [ -r "/opt/csw/include/libxml2/libxml/parser.h" ]; then
  LIBXML_CFLAGS="-I/opt/csw/include/libxml2/"
  LIBXML_LIBS="-L/opt/csw/lib/ -lxml2"
fi
```

**Comment by jlisic** [comment]
Sorry, ended up being a configuration issue, Xcode (gcc/clang) installed but no command line tools.  Not sure how common this is; but it probably isn't worth setting up an edit in your config file.

Thanks,

**Comment by scottmmjackson** [comment]
#235 is related.

Apparently now you have to both install XCode command line tools (`xcode-select --install`) AND install a supplemental package of header files (`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`)
