### ISSUE TITLE
`read_xml()` is 100x faster than `read_html()` when parsing simple XML

### ISSUE THREAD

**Issue by mickeylzj** [hadley/xml2#50]
I'm new here. Maybe this is not a proper issue.
`read_xml()` is 100x faster than `read_html()` when parsing simple XML
Maybe there's something to improve?

the xml file is quite simple:
`<?xml version="1.0" encoding="UTF-8"?>
<i>
  <d>aa</d>
  ...1000 more
</i>`

using `microbenchmark` (mean time)
`read_html` 93.757ms
`read_xml`  1.193ms
`readLines` 1.097ms

Environment:
xml2 version 0.1.2
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.10

**Comment by hadley** [comment]
Not surprising given that it isn't valid HTML.
