### ISSUE TITLE
Feature Request: Coersion to/from xml_nodeset and XML classes

### ISSUE THREAD

**Issue by dbuijs** [hadley/xml2#60]
Apologies if this is already possible (if so then updates to the documentation would be helpful).

It would be helpful if there were ways to coerce vectors and lists into `xml_nodeset` objects without going through `as.character() %>% read_html() %>% html_nodes()`. 

There are two specific use cases I have for this:

1. When accessing REST APIs, it is not uncommon to have arbitrary blobs of HTML embedded in the JSON. I would like to be able to coerce a vector or list of these HTML blobs into the `xml_nodeset` class so that I can use all the wonderful extraction tools of `xml2` and `rvest` on them. Creating a loop or `apply` function creates an awful lot of processing overhead. 

2. Until `xml2` gains XML create/modify functions and something comparable to `XMLtoDataFrame`, I will still need to access the tools in the `XML` package, and right now, that means turning my lovely `xml_nodeset` into characters, parsing them as XML, setting a root node, etc. It would really be very convenient to be able to just coerce an `xml_nodeset` into the appropriate XML object. This is relevant to `xml2` because `xml2` will handle HTTPS connections without supervision, but `XML` needs help. 

I think both use cases get addressed nicely with coercion methods and the appropriate `as` functions. I'm hoping that this shouldn't be too hard to implement since the classes from both packages seem to be special kinds of lists. 

I would also be very happy to be enlightened if there is already a less obvious way of accomplishing these tasks.

**Comment by hadley** [comment]
We'll fix this by adding creation and modification methods to xml2 itself. Should be happening in the next few weeks.

**Comment by jread-usgs** [comment]
"creation and modification methods to xml2 itself" :pizza: :tada: :balloon: !! :+1: You made my weekend.
