### ISSUE TITLE
Serialisation

### ISSUE THREAD

**Issue by hadley** [hadley/xml2#65]
i.e. how to make `saveRDS()` and `readRDS()` work?

**Comment by hadley** [comment]
From Kurt:

> ? XML::xmlSerializeHook
> 
> for a mechanism with user-level hooks, and then
> 
> <http://r.789695.n4.nabble.com/serialization-of-external-pointers-td3552746.html>
>   
>   for a pointer to what Simon seems to do for rJava, and then
> 
> https://www.rforge.net/doc/packages/rJava/jserialize.html
> 
> for more on this.
>

**Comment by hadley** [comment]
I think we just need to serialise as a string and the deserialise on load.

**Comment by jimhester** [comment]
There are three types of objects we would want to serialize.

1. xml_documents - These are easy, just serialize them with `as.character()` and deserialize with `read_xml()`
2. xml_node - Not sure how to deal with the doc ptr, I assume we don't want to serialize the entire document for each node, but maybe there is no other choice... Even if we do how do we ensure the node is pointing to the proper place in the tree?
3. xml_nodesets - Same issues as 2., but each node in the nodeset will have the same document.

Maybe we should just punt on 2. and 3. and only serialize xml_documents?

**Comment by jimhester** [comment]
Another issue, the function given in the `refhook=` parameter of `readRDS()` and `saveRDS()` is called for each external pointer _without_ any context, so while I can serialize and deserialize the document pointer I cannot have the deserialized node pointer point to the deserialized document.

We could fix this by wrapping `readRDS()` and setting the node after deserializing the object, but if we are using our own function how much more useful is this than just using `xml_write()`, `xml_read()` directly...

**Comment by hadley** [comment]
Can you have a look at what XML does?

**Comment by jimhester** [comment]
The main difference is in XML when you `xmlParseDoc()` you get a _single_ external pointer to the document, where we have two pointers to the document and root node. So they can just create the document pointer with the serialized text nodes.

**Comment by hadley** [comment]
Seems pretty hacky, so lets not worry about for now.
