### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by thomasd2** [hadley/xml2#67]
Following up on my post here (https://github.com/hadley/rvest/issues/118#issuecomment-164167439) I reproduced the issue with xml2 version 0.1.2 (and R 3.2.2 and RStudio 0.98.1091) using the following code:

`h <- read_html("tmpminimalutf8.html")`
`h` #  (...umlaut not correctly shown on screen)
`classes <- xml_attr(h,"class")`
`sel1 <- xml_find_all(h, xpath = "body/*")` 
`(classes <- xml_attr(sel1,"class"))` # classes shown correctly on screen
[1] "normalclass"    "umlautclassöäü" "withspace 1"   
`sel2 <- xml_find_all(h, xpath = "body/*[@class='umlautclassöäü']")` 
`sel2` # empty
{xml_nodeset (0)}
`classes[3]`
[1] "withspace 1"
`classes[3] == "withspace 1"` 
[1] FALSE

**Comment by hadley** [comment]
I'd recommend using the reprex package to create a minimal reproducible example that I can actually run. Please include `tmpminimalutf8.html` either inline, or upload it to gist.

**Comment by thomasd2** [comment]
Apologies. Here is the code and the example file (I removed the output below since reprex again changed the encoding from what I see in the RStudio Console).


``` r


library(xml2) # version 0.1.2, with R 3.2.2 and RStudio 0.99.489
h <- read_html("tmpminimalutf8.html")
h #  (umlaut not correctly shown on screen)
classes <- xml_attr(h,"class")
sel1 <- xml_find_all(h, xpath = "body/*") 
(classes <- xml_attr(sel1,"class")) # classes shown correctly on screen
sel2 <- xml_find_all(h, xpath = "body/*[@class='umlautclassöäü']") 
sel2 # is {xml_nodeset (0)}
classes[3]
classes[3] == "withspace 1" # gives FALSE although rhs is what previous line returns on screen
```


[tmpminimalutf8.txt](https://github.com/hadley/xml2/files/62985/tmpminimalutf8.txt)

**Comment by jimhester** [comment]
`classes[3] == "withspace 1"` should not be `TRUE`, because `classes[3]` is actually `whitespace\u00A01`, e.g. a [non-breaking space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) and `"\u00A0" == " "` is `FALSE`.

**Comment by hadley** [comment]
Otherwise all looks ok to me.
