### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by duarteguilherme** [hadley/xml2#68]
I'm trying to initialize a connection with read_xml, but it seems to return an issue with SSL.

I tried this code: 
    
    sucupira = "https://sucupira.capes.gov.br/sucupira/public/consultas/coleta/producaoIntelectual/listaProducaoIntelectual.jsf"
    test <- read_xml(sucupira)

And it returned this error:
  
    Error in open.connection(x, "rb") : 
     Peer certificate cannot be authenticated with given CA certificates

I don't know why this is happening.

Employing httr, this works:

    library(httr)
    set_config( config( ssl_verifypeer = 0L ))
    GET(sucupira)

**Comment by hadley** [comment]
In that case you'll need to use httr to get the file - xml2 has a somewhat simpler networking stack.
