### ISSUE TITLE
When a submit button has no name

### ISSUE THREAD

**Issue by weemax** [hadley/xml2#71]
Not reproducible since I have to give out my account details otherwise

    library(rvest)

    url <- 'https://pro-labs.imdb.com/login'
    pgsession <-html_session(url)
    pgform    <-html_form(pgsession)[[1]]

printing pgform:

    <form> '<unnamed>' (POST )
    <input hidden> 'appToken': 85abc7b28b8aa0e73b56b2cd470569fb56e92fd8
    <input email> 'emailAddress':
    <input password> 'password': 
    <input submit> '': 

how do I fill up a NULL field? lol

    filled_form <- set_values(pgform, emailAddress = "redacted",  password = "redacted")
    submit_form(pgsession,filled_form)

returns:

    Submitting with 'NULL'
    Error: not compatible with STRSXP

How do I get around this?

**Comment by hadley** [comment]
I think you meant to file this on rvest?
