### ISSUE TITLE
enconding issue

### ISSUE THREAD

**Issue by dimitrijoe** [hadley/xml2#74]
I posted [this question in StackOverflow](https://stackoverflow.com/posts/35144449/edit). I am trying to scrape data off tens of thousands of html files using R. [Here's a sample file][1] that one should use to reproduce the problem I describe below.

I am trying to use the xml2 package. The problem I am getting relates to encoding. What is killing me is the fact that this problem was not happening with the XML package. Here's what I am doing:

    library(xml2)    
    
    # paths to input and output files
    input.file = 'C:/tmp/sample_file.html'
    out.file = 'C:/tmp/output_from_xml2.csv'
    
    # read html file as string
    input = readChar(input.file, file.info(input.file)$size)    
        # small hack; consider pre-processing all files and get rid of this hack
        input = gsub(pattern = '&nbsp;?', x = input, perl = T, rep = ' ')     
        
    # parse file
    tree = read_html(input)
        
    # the relevant tables
    tables = xml_find_all(tree, '//table[@id="Tabela_Itens"]')
    
    # the table I am interested in
    mytable = tables[[6]]
        
    # extract table
    cells = xml_find_all(mytable, './/td')
    info = data.frame(matrix(xml_text(cells, trim = T), ncol = 4, byrow = TRUE), stringsAsFactors = FALSE)
    
    # print -- note the gibberish characters
    info[1:5, 4]

     [1] "Licitante"                                                
     [2] "LIDERANÃƒâ€¡A LIMPEZA E CONSERVAÃƒâ€¡ÃƒÆ’O LTDA."         
     [3] "ARTLIMP SERVICOS LTDA"                                    
     [4] "DINÃƒâ€šMICA SERVIÃƒâ€¡OS GERAIS LTDA"                    
     [5] "Servnac TerceirizaÃƒÂ§ÃƒÂ£o Limitada"                     

I tried tweaking the line

    # parse file
    tree = read_html(input)

by passing the argument `encoding`, but no luck.

### `sessionInfo()`:

    > sessionInfo()
    R version 3.2.3 (2015-12-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=English_United Kingdom.1252 
    [2] LC_CTYPE=English_United Kingdom.1252   
    [3] LC_MONETARY=English_United Kingdom.1252
    [4] LC_NUMERIC=C                           
    [5] LC_TIME=English_United Kingdom.1252    

### side note: solution using XML

My first choice was to use the XML package. All good, [except for the memory leak][2], which makes it infeasible to loop over my tens of thousands of files. There doesn't seem to be a simple solution for that. [This document][2], despite all it's good intentions, is not that helpful. 

The solution using XML however does rend correct characters:
   
    library(XML)
    
    #
    input.file = 'C:/tmp/sample_file.html'
    out.file = 'C:/tmp/output_from_xml.csv'
    
    # read html file as string
    input = readChar(input.file, file.info(input.file)$size)    
        # small hack; consider pre-processing all files and get rid of this hack
        input = gsub(pattern = '&nbsp;?', x = input, perl = T, rep = ' ')     
        
    # parse file
    tree = htmlParse(input, encoding = 'UTF-8')
        
    # the relevant tables
    tables = getNodeSet(tree, '//table[@id="Tabela_Itens"]')
    
    # the table I am interested in
    mytable = tables[[6]]
        
    # extract table
    info = readHTMLTable(mytable, colClasses = 'character', header = T)
    
    # print -- that's what I want: latin characters are displayed correctly
    info[1:5, 4]

     [1] LIDERANÇA LIMPEZA E CONSERVAÇÃO LTDA.             
     [2] ARTLIMP SERVICOS LTDA                             
     [3] DINÂMICA SERVIÇOS GERAIS LTDA                     
     [4] Servnac Terceirização Limitada                    
     [5] SATO-SAN SERVIÇOS S/C LTDA. - EPP.                
    15 Levels: APPA SOLUÇÕES EMPRESARIAIS LTDA-ME ...

  
(The two solutions also have small differences -- the header; one is in character, the other has a factor; but I do not worry about those.)

  [1]: https://www.dropbox.com/s/ztnzm35ri2lxszl/sample_file.html?dl=0
  [2]: https://github.com/omegahat/XML/blob/master/Docs/MemoryManagement.pdf

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example that doesn't reference other sites/files?
