### ISSUE TITLE
Complete family tree navigation

### ISSUE THREAD

**Issue by hadley** [hadley/xml2#8]
With `siblings()`, `following()`, `preceding()`, `ancestors()`, `descendants()`

**Comment by MichaelChirico** [comment]
I found myself looking for this today, so surprised to see this closed. I expected `xml_descendants()` to exist. It seems maybe `xml_children()` is intended but that doesn't match my expectation.

In particular, I want a functional equivalent of `xml_find_all(xml, "descendant::*")` On a particular example (I can add a reprex if needed) I found `length(xml_children(xml)) == 84` but `length(xml_find_all(xml, "descendant::*")) == 136`.

**Comment by hadley** [comment]
Can you file a new issue for that?
