### ISSUE TITLE
read_xml vs read_html inconsistency

### ISSUE THREAD

**Issue by mbojan** [hadley/xml2#81]
See below how parsing with `read_html` strangely changes the structure. In `ch` the `ul` is enclosed in `p`. It is properly parsed with `read_xml` but not with `read_html` (`p` is closed before `ul` opens).

``` r
ch <- "
<p>
<ul>
<li>item 1</li>
<li>item 2</li>
</ul>
</p>"

h <- xml2::read_html(ch)
cat( as.character(h) )
#> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
#> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
#> <html><body><p>
#> </p><ul>
#> <li>item 1</li>
#> <li>item 2</li>
#> </ul>
#> </body></html>

x <- xml2::read_xml(ch)
cat(as.character(x))
#> <?xml version="1.0" encoding="UTF-8"?>
#> <p>
#> <ul>
#> <li>item 1</li>
#> <li>item 2</li>
#> </ul>
#> </p>
```

**Comment by hadley** [comment]
Yes, because that's not valid html (you can't put a `<ul>` in a `<p>`)

**Comment by mbojan** [comment]
Can't I? https://www.w3.org/TR/html-markup/p.html says that `<p>` can contain any flow elements, which include `<ul>`.
