### ISSUE TITLE
let user create a namespace?

### ISSUE THREAD

**Issue by jennybc** [hadley/xml2#91]
Would you ever provide a constructor for `xml_namespace` objects?

Context: I want to check that the namespace for a document is what I expect, i.e. assert that current namespace is identical to some reference. But there seems to be no official way to create my reference ... other than creating reference xml and applying `xml_ns()` to it. I know I can create an `xml_namespace` object "by hand", but I'm not sure that's a great idea.

**Comment by jimhester** [comment]
xml_namespace objects are just named character vectors , so you can test against a named character vector and unclass the namespace objects. See [test-namespaces.R#L11-L12](https://github.com/hadley/xml2/blob/248e9fb108704666d48706ca59d5f0140efd3b62/tests/testthat/test-namespaces.R#L11-L12) for an example.
